package lab.operating.system.view;

/**
 *
 * @author C.Mateo
 */
public class MainFrame extends javax.swing.JFrame {
    
    /**
     * Creates new form MainFrame
     */
    
    public MainFrame() {
        initComponents();
    }

    public ProcessPanel getProcessPanel() {
        return processPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        processPanel = new lab.operating.system.view.ProcessPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TASK MANAGER");
        getContentPane().add(processPanel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lab.operating.system.view.ProcessPanel processPanel;
    // End of variables declaration//GEN-END:variables
}
